language: go

go: 1.8

notifications:
    email: false

env:
    - PATH=$HOME/gopath/bin:$PATH

install:
    - go get golang.org/x/tools/cmd/goyacc
    - go get github.com/golang/lint/golint
    - go get -t -v ./... && go build -v ./...

script:
    - ./gok.sh
